
city2mr <- function(city){
# Separa em regiões metropolitanas
  # Região Metropolitana de São Paulo (1)
  RMSP <- c("Arujá",
            "Barueri",
            "Biritiba Mirim",
            "Caieiras",
            "Cajamar",
            "Carapicuíba",
            "Cotia",
            "Diadema",
            "Embu das Artes",
            "Embu-Guaçu",
            "Ferraz de Vasconcelos",
            "Francisco Morato",
            "Franco da Rocha",
            "Guararema",
            "Guarulhos",
            "Itapecerica da Serra",
            "Itapevi",
            "Itaquaquecetuba",
            "Jandira",
            "Juquitiba",
            "Mairiporã",
            "Mauá",
            "Mogi das Cruzes",
            "Osasco",
            "Pirapora do Bom Jesus",
            "Poá",
            "Ribeirão Pires",
            "Rio Grande da Serra",
            "Salesópolis",
            "Santa Isabel",
            "Santana de Parnaíba",
            "Santo André",
            "São Bernardo do Campo",
            "São Caetano do Sul",
            "São Lourenço da Serra",
            "São Paulo",
            "Suzano",
            "Taboão da Serra",
            "Vargem Grande Paulista")
  
  # Região Metropolitana de Campinas (2)
  RMC <- c("Americana",
           "Artur Nogueira",
           "Campinas",
           "Cosmópolis",
           "Engenheiro Coelho",
           "Holambra",
           "Hortolândia",
           "Indaiatuba",
           "Itatiba",
           "Jaguariúna",
           "Monte Mor",
           "Morungaba",
           "Nova Odessa",
           "Paulínia",
           "Santa Bárbara d'Oeste",
           "Santo Antônio de Posse",
           "Sumaré",
           "Valinhos",
           "Vinhedo")
  
  # Região Metropolitana do Vale do Paraíba e Litoral Norte (3)
  RMVale <- c("Aparecida",
              "Arapeí",
              "Areias",
              "Bananal",
              "Caçapava",
              "Cachoeira Paulista",
              "Campos do Jordão",
              "Canas",
              "Caraguatatuba",
              "Cruzeiro",
              "Cunha",
              "Guaratinguetá",
              "Igaratá",
              "Ilhabela",
              "Jacareí",
              "Jambeiro",
              "Lagoinha",
              "Lavrinhas",
              "Lorena",
              "Monteiro Lobato",
              "Natividade da Serra",
              "Paraibuna",
              "Pindamonhangaba",
              "Piquete",
              "Potim",
              "Queluz",
              "Redenção da Serra",
              "Roseira",
              "Santa Branca",
              "Santo Antônio do Pinhal",
              "São Bento do Sapucaí",
              "São José do Barreiro",
              "São José dos Campos",
              "São Luiz do Paraitinga",
              "São Sebastião",
              "Silveiras",
              "Taubaté",
              "Tremembé",
              "Ubatuba")
  
  # Região Metropolitana de Sorocaba (4) 
  RMS <- c("Alambari",
           "Alumínio",
           "Araçariguama",
           "Araçoiaba da Serra",
           "Boituva",
           "Capela do Alto",
           "Cerquilho",
           "Cesário Lange",
           "Ibiúna",
           "Iperó",
           "Itapetininga",
           "Itu",
           "Jumirim",
           "Mairinque",
           "Piedade",
           "Pilar do Sul",
           "Porto Feliz",
           "Salto",
           "Salto de Pirapora",
           "São Miguel Arcanjo",
           "São Roque",
           "Sarapuí",
           "Sorocaba",
           "Tapiraí",
           "Tatuí",
           "Tietê",
           "Votorantim")
  
  # Região Metropolitana da Baixada Santista (5)
  RMBS <- c("Bertioga",
            "Cubatão",
            "Guarujá",
            "Itanhaém",
            "Mongaguá",
            "Peruíbe",
            "Praia Grande",
            "Santos",
            "São Vicente")
  
  # Região Metropolitana de Ribeirão Preto (6) 
  RMRP <- c("Altinópolis",
            "Barrinha",
            "Batatais",
            "Brodowski",
            "Cajuru",
            "Cássia dos Coqueiros",
            "Cravinhos",
            "Dumont",
            "Guariba",
            "Guatapará",
            "Jaboticabal",
            "Jardinópolis",
            "Luiz Antônio",
            "Mococa",
            "Monte Alto",
            "Morro Agudo",
            "Nuporanga",
            "Orlândia",
            "Pitangueiras",
            "Pontal",
            "Pradópolis",
            "Ribeirão Preto",
            "Sales Oliveira",
            "Santa Cruz da Esperança",
            "Santa Rita do Passa Quatro",
            "Santa Rosa de Viterbo",
            "Santo Antônio da Alegria",
            "São Simão",
            "Serra Azul",
            "Serrana",
            "Sertãozinho",
            "Taiuva",
            "Tambaú",
            "Taquaral")
  
  # Aglomeração Urbana de Piracicaba (7)
  AUP <- c("Altinópolis",
           "Barrinha",
           "Batatais",
           "Brodowski",
           "Cajuru",
           "Cássia dos Coqueiros",
           "Cravinhos",
           "Dumont",
           "Guariba",
           "Guatapará",
           "Jaboticabal",
           "Jardinópolis",
           "Luiz Antônio",
           "Mococa",
           "Monte Alto",
           "Morro Agudo",
           "Nuporanga",
           "Orlândia",
           "Piracicaba",
           "Pitangueiras",
           "Pontal",
           "Pradópolis",
           "Ribeirão Preto",
           "Sales Oliveira",
           "Santa Cruz da Esperança",
           "Santa Rita do Passa Quatro",
           "Santa Rosa de Viterbo",
           "Santo Antônio da Alegria",
           "São Simão",
           "Serra Azul",
           "Serrana",
           "Sertãozinho",
           "Taiuva",
           "Tambaú",
           "Taquaral")
  
  # Aglomeração Urbana de Jundiaí (8)
  AGJ <- c("Cabreúva",
           "Campo Limpo Paulista",
           "Itupeva",
           "Jarinu",
           "Jundiaí",
           "Louveira",
           "Várzea Paulista")
  
  # Aglomeração Urbana de Franca (9)
  AUF <- c("Buritizal",
           "Aramina",
           "Cristais Paulista",
           "Franca",
           "Guaíra",
           "Guará",
           "Igarapava",
           "Ipuã",
           "Itirapuã",
           "Ituverava",
           "Jeriquara",
           "Miguelópolis",
           "Patrocínio Paulista",
           "Pedregulho",
           "Restinga",
           "Ribeirão Corrente",
           "Rifaina",
           "São Joaquim da Barra",
           "São José da Bela Vista")

  if(city %in% RMSP){return("RMSP")}
  if(city %in% RMC){return("RMC")}
  if(city %in% RMVale){return("RMVale")}
  if(city %in% RMS){return("RMS")}
  if(city %in% RMBS){return("RMBS")}
  if(city %in% RMRP){return("RMRP")}
  if(city %in% AUP){return("AUP")}
  if(city %in% AGJ){return("AGJ")}
  if(city %in% AUF){return("AUF")}
  else {return("OTHERS")}    
}
